name: ultrack-i2k2023
channels:
  - gurobi
  - conda-forge
  - defaults
dependencies:
  - cellpose
  - coin-or-cbc
  - gurobi
  - jupyter
  - nodejs
  - pip
  - pyqt
  - stackview
  - pip:
    - git+https://github.com/higra/Higra
    - git+https://github.com/Janelia-Trackathon-2023/traccuracy
    - napari
    - ultrack
